name: mego_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.4
  google_sign_in: ^6.1.5
  video_player: ^2.10.1
  url_launcher: ^6.1.7
  random_string: ^2.3.1
  lottie: ^3.0.0
  google_maps_flutter: ^2.5.0
  firebase_messaging: ^15.1.3
  awesome_snackbar_content:
  geolocator: ^9.0.2
  whatsapp_unilink: ^2.0.0
  get_storage: ^2.1.1
  geocoding:
  get: ^4.6.6
  get_it: ^8.2.0
  flutter_svg: ^1.1.6
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  flutter_carousel_slider: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.3.1
  flutter_onboarding_slider: ^1.0.10
  http: ^0.13.5
  change_app_package_name: ^1.0.0
  googleapis_auth: ^1.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mLogo.png"
  remove_alpha: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    # Default App Font - Montserrat
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400  # Regular weight (using Medium as regular)
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
    
    # Secondary Fonts
    - family: fs_albert
      fonts:
        - asset: assets/fonts/fs_albert.ttf
          weight: 400
    
    # Inter 18pt Family
    - family: Inter18pt
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-Black.ttf
          weight: 900
    
    # Inter 28pt Family
    - family: Inter28pt
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_28pt-ThinItalic.ttf
          weight: 100
          style: italic
    
    # Roboto Condensed Family
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/Roboto_Condensed-Medium.ttf
          weight: 400  # Using Medium as regular
        - asset: assets/fonts/Roboto_Condensed-MediumItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto_Condensed-LightItalic.ttf
          weight: 300
          style: italic
